# Welcome to numpy tutorial

In [65]:
import numpy as np

In [66]:
myarr = np.array([[3 , 6 , 32 , 7]] , np.int64)

In [67]:
myarr[0 , 1]

np.int64(6)

In [68]:
myarr.shape

(1, 4)

In [69]:
myarr.dtype

dtype('int64')

In [70]:
myarr[0 , 1] = 45

In [71]:
myarr

array([[ 3, 45, 32,  7]])

# Array Creation : Conversion from other Python structures (i.e. lists and tuples)

In [72]:
listarray = np.array([[1 , 2 , 3] , [5, 8 , 5] , [0 , 3 , 1]])

In [61]:
listarray


array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [62]:
listarray.dtype

dtype('int64')

In [63]:
listarray.shape

(3, 3)

In [64]:
listarray.size

9

In [65]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [66]:
zeros = np.zeros((2 , 5))

In [67]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
rng = np.arange(15)

In [69]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
lspace= np.linspace(1 , 5 , 4)

In [71]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [72]:
emp = np.empty((4 , 6))

In [73]:
emp

array([[1.09129174e-311, 2.89661738e-315, 0.00000000e+000,
        0.00000000e+000, 1.09070584e-311, 5.30276956e+180],
       [6.00736842e-067, 5.38016467e+097, 1.38401415e-047,
        4.26262627e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        3.44192131e+175, 1.38053976e-047, 5.58409934e-091],
       [7.27309743e-043, 2.59027862e-144, 1.16442250e-028,
        9.44872517e-143, 6.17582057e-322, 2.22507386e-308]])

In [74]:
emp_like = np.empty_like(lspace)

In [75]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [76]:
ide = np.identity(45)

In [77]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [78]:
ide.shape

(45, 45)

In [79]:
arr = np.arange(99)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [81]:
arr = arr.reshape(3 , 33)

In [82]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [83]:
arr = arr.ravel()

In [84]:
arr.shape

(99,)

In [85]:
x = [[1 , 2 , 3] , [4 , 5 , 6] , [7 , 1 , 0]]

In [86]:
ar = np.array(x)

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
ar.sum(axis = 0)

array([12,  8,  9])

In [89]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [90]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [91]:
ar.flat

In [92]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [93]:
ar.ndim

2

In [94]:
ar.size

9

In [95]:
ar.nbytes

72

In [96]:
one = np.array([1 , 3 , 4 , 634 , 2])

In [97]:
one.argmax()

np.int64(3)

In [98]:
one.argmin()

np.int64(0)

In [99]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [100]:
ar.argmin()

np.int64(8)

In [101]:
ar.argmax()

np.int64(6)

In [102]:
ar.argmin(axis = 0)

array([0, 2, 2])

In [103]:
ar.argmin(axis = 1)

array([0, 0, 2])

In [104]:
ar.argmax(axis = 0)

array([2, 1, 1])

In [105]:
ar.argmax(axis = 1)

array([2, 2, 0])

In [106]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [107]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [108]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [109]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [112]:
ar.reshape((9 ,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [113]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [114]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [115]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [116]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [117]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [118]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [119]:
ar.sum()

np.int64(29)

In [120]:
ar.max()

np.int64(7)

In [121]:
ar.min()

np.int64(0)

In [122]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [125]:
np.where(ar > 5)

(array([1, 2]), array([2, 0]))

In [126]:
np.count_nonzero(ar)

np.int64(8)

In [131]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [132]:
ar[1 , 2] = 0

In [133]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [134]:
import sys

In [142]:
py_ar = [0,4,55,2]

In [143]:
np_ar = np.array(py_ar)

In [144]:
sys.getsizeof(1) * len(py_ar)

112

In [145]:
np_ar.itemsize * np_ar.size

32

In [146]:
np_ar.tolist()

[0, 4, 55, 2]